### ISSUE TITLE
Roboko ne nous prévient pas de la création d'article quand le bandeau ABDA a été ajouté après la création.

### ISSUE THREAD

**Issue by Thibaut120094** [0x010C/Roboko#14]
Exemples : 
- https://fr.wikipedia.org/w/index.php?title=Magical_Girl_Site&action=history
- https://fr.wikipedia.org/w/index.php?title=Boruto:_Naruto_the_Movie&action=history

**Comment by Thibaut120094** [comment]
Quid des pages créées après déplacement depuis une sous-page utilisateur ?
https://fr.wikipedia.org/w/index.php?title=Secret_%28manga%29&action=history

**Comment by 0x010C** [comment]
Done in 6734ef1
