### ISSUE TITLE
Avertir des changements de catégorie

### ISSUE THREAD

**Issue by 0x010C** [0x010C/Roboko#6]
Mettre un message d'avertissement dans le chan lorsqu'un contributeur sous IP modifie la "catégorie" d'un article du projet ABDA (genre shōjo and co)

**Comment by Thibaut120094** [comment]
Ouaip, faudrait surveiller les changements effectués par des IP sur les champs suivants :

```
{{Infobox Animation et bande dessinée asiatiques/Entête
 | type          = 
}}

{{Infobox Animation et bande dessinée asiatiques/Livre
 | public_cible        = 
}}

```

Merci !
