### ISSUE TITLE
Flux RSS

### ISSUE THREAD

**Issue by Thibaut120094** [0x010C/Roboko#7]
Diffuser les flux RSS d'ANN et d'Animeland sur le chan peut être pratique pour mettre à jour les articles.
- http://www.animenewsnetwork.com/news/rss.xml
- http://www.animeland.com/rss/news

À noter qu'on peut raccourcir les liens d'ANN, exemple : 
http://www.animenewsnetwork.com/daily-briefs/2015-03-15/girls-and-panzer-film-theme-singer-date-length-new-visual-unveiled/.85983
par http://4nn.cx/.85983

Même chose pour Animeland :
http://www.animeland.com/news/voir/8702/Nisekoi-saison-2-en-avril-sur-ADN
par http://www.animeland.com/news/voir/8702/

Juste afficher le nom du site [ANN / Animeland], le titre de l'article, puis l'URL court.

**Comment by Thibaut120094** [comment]
Au cas où ça flood trop, faire une commande !rss on/off !rss ann/animeland on/off

**Comment by 0x010C** [comment]
Voir commit c9164cf052010850ebf3039d97c15bad4eddfd6e (Apr 6 23:46:29 2015 +0200)
